//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NValidator.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be one of the allowed values. Allowed values: @AllowedValues..
        /// </summary>
        public static string NValidator_Validators_AllowedValuesValidator_GetErrors {
            get {
                return ResourceManager.GetString("NValidator_Validators_AllowedValuesValidator_GetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must not be one of the following values: @ProhibitValues..
        /// </summary>
        public static string NValidator_Validators_AllowedValuesValidator_GetNegatableErrors {
            get {
                return ResourceManager.GetString("NValidator_Validators_AllowedValuesValidator_GetNegatableErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must equal to @ComparisonValue..
        /// </summary>
        public static string NValidator_Validators_EqualValidator_Message {
            get {
                return ResourceManager.GetString("NValidator_Validators_EqualValidator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be greater than or equal @ComparisonValue..
        /// </summary>
        public static string NValidator_Validators_GreaterThanOrEqualValidator_Message {
            get {
                return ResourceManager.GetString("NValidator_Validators_GreaterThanOrEqualValidator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be greater than @ComparisonValue..
        /// </summary>
        public static string NValidator_Validators_GreaterThanValidator_Message {
            get {
                return ResourceManager.GetString("NValidator_Validators_GreaterThanValidator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be null..
        /// </summary>
        public static string NValidator_Validators_IsNullValidator_GetErrors {
            get {
                return ResourceManager.GetString("NValidator_Validators_IsNullValidator_GetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must not be null..
        /// </summary>
        public static string NValidator_Validators_IsNullValidator_GetNegatableErrors {
            get {
                return ResourceManager.GetString("NValidator_Validators_IsNullValidator_GetNegatableErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be between @MinimumLength and @MaximumLength in length. You had @TotalLength in length..
        /// </summary>
        public static string NValidator_Validators_LengthValidator_GetValidationResult {
            get {
                return ResourceManager.GetString("NValidator_Validators_LengthValidator_GetValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be less than or equal @ComparisonValue..
        /// </summary>
        public static string NValidator_Validators_LessThanOrEqualValidator_Message {
            get {
                return ResourceManager.GetString("NValidator_Validators_LessThanOrEqualValidator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be less than @ComparisonValue..
        /// </summary>
        public static string NValidator_Validators_LessThanValidator_Message {
            get {
                return ResourceManager.GetString("NValidator_Validators_LessThanValidator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName cannot be empty..
        /// </summary>
        public static string NValidator_Validators_NotEmptyValidator_GetValidationResult {
            get {
                return ResourceManager.GetString("NValidator_Validators_NotEmptyValidator_GetValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must not equal to @ComparisonValue..
        /// </summary>
        public static string NValidator_Validators_NotEqualValidator_Message {
            get {
                return ResourceManager.GetString("NValidator_Validators_NotEqualValidator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must not be null..
        /// </summary>
        public static string NValidator_Validators_NotNullValidator_GetErrors {
            get {
                return ResourceManager.GetString("NValidator_Validators_NotNullValidator_GetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName must be null..
        /// </summary>
        public static string NValidator_Validators_NotNullValidator_GetNegatableErrors {
            get {
                return ResourceManager.GetString("NValidator_Validators_NotNullValidator_GetNegatableErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PropertyName does not match condition..
        /// </summary>
        public static string NValidator_Validators_PredicateValidator_GetValidationResult {
            get {
                return ResourceManager.GetString("NValidator_Validators_PredicateValidator_GetValidationResult", resourceCulture);
            }
        }
    }
}
